import type { Database, Entry, Layout } from "./model";
const stamp = "2026-10-08T09:00:00.000Z";
const entry = (
  e: Partial<Entry> &
    Pick<Entry, "id" | "title" | "description" | "kind" | "category">,
): Entry => ({
  author: "gameslash",
  url: "",
  sourceUrl: "",
  image: "",
  body: "",
  tags: [],
  status: "published",
  createdAt: stamp,
  updatedAt: stamp,
  ...e,
});
const entries: Entry[] = [
  entry({
    id: "suck-up",
    kind: "game",
    title: "Suck Up!",
    description:
      "เป็นแวมไพร์เจ้าเสน่ห์ ใช้ไหวพริบและบทสนทนากับตัวละคร AI เพื่อให้พวกเขาเชิญคุณเข้าบ้าน",
    author: "Proxima",
    category: "ผจญภัย",
    url: "https://www.playsuckup.com/",
    sourceUrl: "https://www.playsuckup.com/",
    image: "/images/suck-up-scene.webp",
    tags: ["AI ในเกม", "PC", "บทสนทนา"],
    body: "การผจญภัยที่คำพูดของคุณเป็นส่วนหนึ่งของเกม ลองสวมบทบาท เปลี่ยนวิธีพูด และรับมือกับคำตอบของตัวละคร\n\nดูราคา แพลตฟอร์ม และข้อกำหนดล่าสุดได้จากเว็บไซต์ผู้พัฒนา",
  }),
  entry({
    id: "infinite-craft",
    kind: "game",
    title: "Infinite Craft",
    description:
      "เริ่มจากธาตุเพียงสี่อย่าง แล้วจับคู่สิ่งต่าง ๆ เพื่อค้นพบความเป็นไปได้แบบไม่สิ้นสุด",
    author: "Neal Agarwal",
    category: "ปริศนา",
    url: "https://neal.fun/infinite-craft/",
    sourceUrl: "https://neal.fun/infinite-craft/",
    image: "",
    tags: ["AI ในเกม", "เว็บ", "สร้างสรรค์"],
  }),
  entry({
    id: "ai-dungeon",
    kind: "game",
    title: "AI Dungeon",
    description:
      "เลือกโลกของคุณ พิมพ์สิ่งที่อยากทำ แล้วร่วมเขียนการผจญภัยไปกับผู้เล่าเรื่อง AI",
    author: "Latitude",
    category: "RPG",
    url: "https://aidungeon.com/",
    sourceUrl: "https://aidungeon.com/",
    image: "/images/ai-dungeon.png",
    tags: ["AI ในเกม", "เว็บ", "เล่าเรื่อง"],
  }),
  entry({
    id: "narrator",
    kind: "game",
    title: "Narrator",
    description:
      "ออกเดินทางในเรื่องราวสวมบทบาทที่ AI ช่วยเล่า และเลือกทิศทางการผจญภัยด้วยตัวคุณเอง",
    author: "Narrator",
    category: "RPG",
    url: "https://playnarrator.com/",
    sourceUrl: "https://playnarrator.com/",
    image: "/images/narrator.png",
    tags: ["AI ในเกม", "เล่าเรื่อง"],
  }),
  entry({
    id: "agent-breaker",
    kind: "game",
    title: "Agent Breaker",
    description:
      "ลองท้าทายระบบ AI ของ Lakera ด้วยคำสั่งและกลยุทธ์การสนทนาของคุณ",
    author: "Lakera",
    category: "ปริศนา",
    url: "https://play.lakera.ai/agent-breaker",
    sourceUrl: "https://play.lakera.ai/agent-breaker",
    image: "/images/agent-breaker.jpeg",
    tags: ["AI ในเกม", "เว็บ", "ทดลอง"],
  }),
  entry({
    id: "ai-town",
    kind: "game",
    title: "AI Town",
    description:
      "สำรวจเมืองจำลองของตัวละคร AI ที่พูดคุยและใช้ชีวิตร่วมกัน พร้อมโค้ดต้นแบบให้ศึกษา",
    author: "Convex",
    category: "จำลอง",
    url: "https://www.convex.dev/ai-town",
    sourceUrl: "https://github.com/a16z-infra/ai-town",
    image: "",
    tags: ["AI ในเกม", "โอเพนซอร์ส", "ทดลอง"],
  }),
  entry({
    id: "claude",
    kind: "tool",
    title: "Claude",
    description: "ผู้ช่วย AI สำหรับคิดระบบเกม อธิบายโค้ด และทดลองสร้างต้นแบบ",
    author: "Anthropic",
    category: "เขียนโค้ด",
    url: "https://claude.ai/",
    tags: ["โค้ด", "ต้นแบบ"],
  }),
  entry({
    id: "godot",
    kind: "tool",
    title: "Godot",
    description: "เอนจินโอเพนซอร์สสำหรับสร้างเกม 2D และ 3D พร้อมเอกสารเริ่มต้น",
    author: "Godot Foundation",
    category: "เอนจินเกม",
    url: "https://godotengine.org/",
    tags: ["โอเพนซอร์ส", "2D / 3D"],
  }),
  entry({
    id: "itch-io",
    kind: "tool",
    title: "itch.io",
    description: "พื้นที่เผยแพร่เกมอินดี้และทดลองแจกเกมของคุณให้ผู้เล่น",
    author: "itch.io",
    category: "เผยแพร่",
    url: "https://itch.io/",
    tags: ["เผยแพร่", "ชุมชน"],
  }),
  entry({
    id: "blender",
    kind: "tool",
    title: "Blender",
    description: "สร้างโมเดล ฉาก และแอนิเมชั่น 3D เพื่อนำไปใช้ในเกม",
    author: "Blender Foundation",
    category: "โมเดล 3D",
    url: "https://www.blender.org/",
    tags: ["โอเพนซอร์ส", "3D"],
  }),
  entry({
    id: "first-small-game",
    kind: "article",
    title: "เกมแรกไม่ต้องใหญ่ แค่มีอะไรให้ลองเล่น",
    description:
      "จากไอเดียหนึ่งประโยค ไปสู่ต้นแบบที่ส่งให้เพื่อนลองได้ เริ่มเล็กแค่ไหนถึงจะพอดี?",
    category: "เริ่มต้นทำเกม",
    image: "",
    tags: ["เริ่มต้น", "5 นาที"],
    body: "เริ่มด้วยการกระทำเดียว\n\nเขียนให้ได้ว่าผู้เล่นทำอะไร เช่น จับคู่ธาตุ หลบสิ่งกีดขวาง หรือถามคำถามตัวละคร เลือกเพียงอย่างเดียวเป็นแกนของต้นแบบ\n\nกำหนดขอบเขตให้จบได้\n\nใช้ฉากเดียว เป้าหมายเดียว และวิธีควบคุมที่อธิบายได้ในหนึ่งประโยค ภาพชั่วคราวและเสียงง่าย ๆ เพียงพอสำหรับทดสอบว่าเกมสนุกหรือไม่\n\nให้ AI ช่วยทีละส่วน\n\nอธิบายสิ่งที่ต้องการและผลที่คาดหวังให้ชัด ขอให้ช่วยงานเล็กทีละชิ้น แล้วทดลองหลังเปลี่ยนทุกครั้ง อย่าใส่รหัสผ่านหรือข้อมูลลับลงในโค้ดฝั่งผู้เล่น\n\nส่งให้คนอื่นลอง\n\nสังเกตว่าผู้เล่นเข้าใจเป้าหมายหรือไม่ ติดตรงไหน และอยากเล่นอีกรอบหรือเปล่า ใช้สิ่งที่เห็นตัดสินใจว่าควรปรับอะไรต่อ",
  }),
  entry({
    id: "share-your-game",
    kind: "article",
    title: "ก่อนแชร์เกม ส่งอะไรให้คนอยากกดดู?",
    description:
      "ชื่อที่จำได้ ภาพที่เข้าใจ และลิงก์ที่เปิดได้จริง คือจุดเริ่มต้นที่ดีของการแนะนำเกม",
    category: "เผยแพร่ผลงาน",
    image: "",
    tags: ["เผยแพร่", "3 นาที"],
    body: "เล่าว่าเกมมีอะไรให้ทำ\n\nคำอธิบายสั้นควรบอกว่าผู้เล่นทำอะไรและอะไรทำให้เกมต่างออกไป ลองเริ่มด้วยกริยาแทนรายชื่อเทคโนโลยี\n\nเลือกภาพที่แทนเกมได้จริง\n\nใช้ภาพจากเกมหรือภาพประชาสัมพันธ์ที่คุณมีสิทธิ์ใช้ หากเป็นภาพประกอบ ให้บอกตรง ๆ ว่าไม่ใช่ภาพการเล่น\n\nทดสอบลิงก์ก่อนส่ง\n\nเปิดลิงก์ในหน้าต่างที่ไม่ได้ล็อกอิน และลองบนอุปกรณ์เป้าหมาย ระบุให้ชัดหากต้องซื้อ ดาวน์โหลด หรือลงชื่อเข้าใช้\n\nให้เครดิตผู้ร่วมสร้าง\n\nระบุผู้พัฒนา เครื่องมือ และแหล่งที่มาของทรัพยากรตามเงื่อนไขของเจ้าของผลงาน แล้วส่งลิงก์ให้ทีม gameslash ตรวจรายการได้เลย",
  }),
  entry({
    id: "welcome-builders",
    kind: "post",
    title: "กำลังทำเกมอะไรอยู่? มาแชร์ไอเดียกัน",
    description:
      "พื้นที่เล็ก ๆ ของคนชอบสร้างเกม แนะนำโปรเจกต์ เล่าสิ่งที่กำลังลอง หรือส่งคำถามที่อยากคุย",
    category: "พูดคุย",
    tags: ["จากทีมงาน"],
    body: "ยินดีต้อนรับสู่ gameslash\n\nเราอยากให้ที่นี่เป็นจุดเริ่มต้นของการเจอเกมและคนทำเกมใหม่ ๆ แชร์ผลงาน ขอฟีดแบ็ก หรือเล่าบทเรียนจากการทำเกมของคุณผ่านปุ่มส่งโพสต์\n\nโพสต์จะผ่านการตรวจโดยทีมงานก่อนแสดงบนหน้าเว็บ เพื่อให้พื้นที่นี้อ่านง่ายและเกี่ยวข้องกับการทำเกม",
  }),
];
const layout: Layout = {
  spotlights: [],
  tagline: "เกมใหม่ ไอเดียใหม่ ความเป็นไปได้ไม่สิ้นสุด",
  categories: [
    "RPG",
    "ผจญภัย",
    "ปริศนา",
    "จำลอง",
    "สยองขวัญ",
    "วางแผน",
    "ปาร์ตี้",
  ],
  featuredIds: [
    "suck-up",
    "infinite-craft",
    "ai-dungeon",
    "narrator",
    "ai-town",
  ],
  sections: [
    {
      id: "discover",
      title: "ใหม่ล่าสุด",
      kind: "game",
      template: "shelf",
      category: "",
      enabled: true,
    },
    {
      id: "rpg",
      title: "RPG",
      kind: "game",
      template: "shelf",
      category: "RPG",
      enabled: true,
    },
    {
      id: "puzzle",
      title: "ปริศนา",
      kind: "game",
      template: "shelf",
      category: "ปริศนา",
      enabled: true,
    },
    {
      id: "adventure",
      title: "ผจญภัย",
      kind: "game",
      template: "shelf",
      category: "ผจญภัย",
      enabled: true,
    },
    {
      id: "simulation",
      title: "จำลอง",
      kind: "game",
      template: "shelf",
      category: "จำลอง",
      enabled: true,
    },
  ],
};
export function seedDatabase(): Database {
  return structuredClone({
    version: 1,
    customTags: [],
    tagRequests: [],
    revision: 0,
    entries,
    layout,
    draftLayout: structuredClone(layout),
    limits: {},
    agents: [],
    oauthCodes: [],
    oauthGrants: [],
    activity: [],
    ingestions: {},
    reviews: {},
    sources: [],
    collectionBudget: null,
    collectionJobs: [],
    provenance: {},
  });
}
