import test from "node:test";
import assert from "node:assert/strict";
import { seedDatabase } from "../src/lib/seed";
import { databaseSchema, entryInput, publicData, type Database } from "../src/lib/model";
import { manageCatalog, authenticateAgent, createAgentDraft, editAgentDraft, agentEntries } from "../src/lib/catalog-service";
const input = () => entryInput.parse({ ...seedDatabase().entries[0], url: "https://example.com/agent-test" });
function key(db: Database, write = true) {
  const token = manageCatalog(db, { action: "create_agent", revision: db.revision, name: "Test agent", canWriteDrafts: write })!;
  return { token, agent: authenticateAgent(db, token)! };
}
test("old catalogs default agent metadata; keys are hashed, expire and revoke", () => {
  const { agents: _a, activity: _b, ingestions: _c, reviews: _d, ...legacy } = seedDatabase();
  const db = databaseSchema.parse(legacy);
  assert.deepEqual(db.agents, []);
  assert.deepEqual(db.reviews, {});
  const { token, agent } = key(db);
  assert.ok(agent);
  assert.equal(JSON.stringify(db).includes(token), false);
  assert.equal(authenticateAgent(db, "bad"), null);
  assert.equal(authenticateAgent(db, token.slice(0, -1) + (token.endsWith("a") ? "b" : "a")), null);
  agent.expiresAt = "2020-01-01T00:00:00.000Z";
  assert.equal(authenticateAgent(db, token), null);
  agent.expiresAt = "2099-01-01T00:00:00.000Z";
  manageCatalog(db, { action: "revoke_agent", revision: db.revision, id: agent.id });
  assert.equal(authenticateAgent(db, token), null);
  assert.throws(() => createAgentDraft(db, agent.id, "request-1", input()), /ไม่มีสิทธิ์/);
  for (const privateField of ["agents", "activity", "ingestions", "limits", "reviews"]) assert.equal(privateField in publicData(db), false);
});
test("review returns feedback, allows resubmission, and only publishes pending entries", () => {
  const db = seedDatabase(), { agent } = key(db);
  const context = { provider: "Apify", runId: "example-run", reason: "Public creator post with an original game link." };
  const draft = createAgentDraft(db, agent.id, "context-request", input(), context);
  assert.deepEqual(db.ingestions[draft.id].context, context);
  assert.equal(createAgentDraft(db, agent.id, "context-request", input(), context).id, draft.id);
  assert.throws(() => createAgentDraft(db, agent.id, "context-request", input(), { ...context, reason: "Different collection explanation" }), /requestId/);
  const review = (decision: "publish" | "return" | "reject", note: string, updatedAt: string) => manageCatalog(db, { action: "review", revision: db.revision, id: draft.id, expectedUpdatedAt: updatedAt, decision, note });
  assert.throws(() => review("publish", "", draft.updatedAt), /รอตรวจ/);
  const pending = editAgentDraft(db, agent.id, draft.id, draft.updatedAt);
  assert.throws(() => review("return", "", pending.updatedAt), /เหตุผล/);
  assert.throws(() => review("reject", "", pending.updatedAt), /เหตุผล/);
  assert.throws(() => review("publish", "", draft.updatedAt), /ข้อมูลล่าสุด/);
  review("return", "Please verify creator credit", pending.updatedAt);
  assert.equal(db.entries[0].status, "draft");
  assert.equal(db.reviews[draft.id].note, "Please verify creator credit");
  const fixed = editAgentDraft(db, agent.id, draft.id, db.entries[0].updatedAt, { ...input(), author: "Verified creator" });
  const again = editAgentDraft(db, agent.id, draft.id, fixed.updatedAt);
  review("publish", "Checked against source", again.updatedAt);
  assert.equal(db.entries[0].status, "published");
  assert.equal(db.reviews[draft.id].decision, "publish");
  assert.equal(JSON.stringify(publicData(db)).includes("Checked against source"), false);
  assert.throws(() => review("return", "Already published", db.entries[0].updatedAt), /รอตรวจ/);
  databaseSchema.parse(db);
});
test("rejecting archives instead of deleting the submission", () => {
  const db = seedDatabase(), { agent } = key(db);
  const draft = createAgentDraft(db, agent.id, "reject-request", input());
  const pending = editAgentDraft(db, agent.id, draft.id, draft.updatedAt);
  manageCatalog(db, { action: "review", revision: db.revision, id: draft.id, expectedUpdatedAt: pending.updatedAt, decision: "reject", note: "Off topic" });
  assert.equal(db.entries[0].id, draft.id);
  assert.equal(db.entries[0].status, "archived");
  assert.equal(db.reviews[draft.id].note, "Off topic");
});
test("draft retries are idempotent, duplicate URLs and changed request payloads rejected", () => {
  const db = seedDatabase(), { agent } = key(db);
  const draft = createAgentDraft(db, agent.id, "request-1", input());
  const count = db.activity.length;
  assert.deepEqual(createAgentDraft(db, agent.id, "request-1", input()), draft);
  assert.equal(db.activity.length, count);
  assert.equal(db.limits[`agent:${agent.id}`].count, 1);
  assert.throws(() => createAgentDraft(db, agent.id, "request-1", { ...input(), title: "Different" }), /requestId/);
  assert.throws(() => createAgentDraft(db, agent.id, "request-2", input()), /มีลิงก์/);
  assert.equal(draft.status, "draft");
});
test("agents cannot access other drafts, overwrite changes, publish, or modify reviewed work", () => {
  const db = seedDatabase(), first = key(db), second = key(db), reader = key(db, false);
  const draft = createAgentDraft(db, first.agent.id, "request-1", input());
  assert.equal(agentEntries(db, second.agent.id).some(e => e.id === draft.id), false);
  assert.throws(() => editAgentDraft(db, second.agent.id, draft.id, draft.updatedAt, input()), /สร้างเอง/);
  assert.throws(() => createAgentDraft(db, reader.agent.id, "request-1", input()), /ไม่มีสิทธิ์/);
  const changed = editAgentDraft(db, first.agent.id, draft.id, draft.updatedAt, { ...input(), title: "Updated draft" });
  assert.notEqual(changed.updatedAt, draft.updatedAt);
  assert.throws(() => editAgentDraft(db, first.agent.id, draft.id, draft.updatedAt, input()), /ข้อมูลล่าสุด/);
  const pending = editAgentDraft(db, first.agent.id, changed.id, changed.updatedAt);
  assert.equal(pending.status, "pending");
  assert.equal(publicData(db).entries.some(e => e.id === draft.id), false);
  assert.throws(() => editAgentDraft(db, first.agent.id, pending.id, pending.updatedAt, input()), /สร้างเอง/);
  manageCatalog(db, { action: "entry", revision: db.revision, entry: { ...pending, status: "published" } });
  assert.ok(publicData(db).entries.some(e => e.id === draft.id));
  assert.throws(() => editAgentDraft(db, first.agent.id, draft.id, db.entries[0].updatedAt, input()), /สร้างเอง/);
  databaseSchema.parse(db);
});
test("agent write limits and recent activity cap are enforced", () => {
  const db = seedDatabase(), { agent } = key(db);
  db.limits[`agent:${agent.id}`] = { count: 60, reset: Date.now() + 60000 };
  assert.throws(() => createAgentDraft(db, agent.id, "request-1", input()), /บ่อยเกินไป/);
  for (let i = 0; i < 205; i++) manageCatalog(db, { action: "layout", revision: db.revision, layout: db.layout, publish: false });
  assert.equal(db.activity.length, 200);
});

test("only inactive MCP keys can be deleted without losing content history", () => {
  const db = seedDatabase(), { token, agent } = key(db);
  assert.throws(() => manageCatalog(db, { action: "delete_agent", revision: db.revision, id: agent.id }), /ยกเลิกคีย์ก่อน/);
  db.ingestions["historical-entry"] = { agentId: agent.id, inputHash: "a".repeat(64) };
  manageCatalog(db, { action: "revoke_agent", revision: db.revision, id: agent.id });
  manageCatalog(db, { action: "delete_agent", revision: db.revision, id: agent.id });
  assert.equal(db.agents.some(a => a.id === agent.id), false);
  assert.equal(authenticateAgent(db, token), null);
  assert.equal(db.ingestions["historical-entry"].agentId, agent.id);
  assert.ok(db.activity.some(a => a.action === "agent.deleted" && a.title === agent.name));
  databaseSchema.parse(db);
});

test("trash hides published content and restores its previous status", () => {
  const db = seedDatabase();
  const original = db.entries.find(e => e.status === "published")!;
  assert.ok(publicData(db).entries.some(e => e.id === original.id));
  manageCatalog(db, { action: "trash_entry", revision: db.revision, id: original.id, expectedUpdatedAt: original.updatedAt });
  const trashed = db.entries.find(e => e.id === original.id)!;
  assert.equal(trashed.status, "archived");
  assert.equal(trashed.restoreStatus, "published");
  assert.equal(publicData(db).entries.some(e => e.id === original.id), false);
  assert.throws(() => manageCatalog(db, { action: "restore_entry", revision: db.revision, id: original.id, expectedUpdatedAt: original.updatedAt }), /ข้อมูลล่าสุด/);
  manageCatalog(db, { action: "restore_entry", revision: db.revision, id: original.id, expectedUpdatedAt: trashed.updatedAt });
  const restored = db.entries.find(e => e.id === original.id)!;
  assert.equal(restored.status, "published");
  assert.equal(restored.restoreStatus, undefined);
  assert.ok(publicData(db).entries.some(e => e.id === original.id));
  const older = { ...restored, status: "archived" as const };
  delete (older as Partial<typeof older>).restoreStatus;
  db.entries = db.entries.map(e => e.id === older.id ? older : e);
  manageCatalog(db, { action: "restore_entry", revision: db.revision, id: older.id, expectedUpdatedAt: older.updatedAt });
  assert.equal(db.entries.find(e => e.id === older.id)?.status, "draft");
  databaseSchema.parse(db);
});
