"use client";
import { useState } from "react";
import { Search, Plus, Pencil, FileText, Gamepad2, Wrench, MessagesSquare, ChevronLeft, ChevronRight, ArrowUpRight } from "lucide-react";
import { kindLabels, type Entry } from "@/lib/model";
const statusLabels={published:"เผยแพร่แล้ว",pending:"รอตรวจ",draft:"ฉบับร่าง",archived:"เก็บเข้าคลัง"};
const icons={game:Gamepad2,article:FileText,tool:Wrench,post:MessagesSquare};
export function ContentLibrary({entries,edit,create,review}:{entries:Entry[];edit:(entry:Entry)=>void;create:()=>void;review:(entry:Entry)=>void}) {
  const [status,setStatus]=useState("active"),[kind,setKind]=useState("all"),[query,setQuery]=useState(""),[page,setPage]=useState(1);
  const items=entries.filter(e=>(status==="active"?e.status!=="archived":e.status===status)&&(kind==="all"||kind===e.kind)&&`${e.title} ${e.author} ${e.category}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));
  const pages=Math.max(1,Math.ceil(items.length/20)),current=Math.min(page,pages);
  return <section className="content-library">
    <div className="studio-heading"><div><span className="eyebrow">CONTENT LIBRARY</span><h1>คลังเนื้อหา</h1><p>เกม บทความ และเครื่องมือ — ค้นหาแล้วเปิดจัดการได้ทันที</p></div><button className="button primary" onClick={create}><Plus size={18}/>เพิ่มรายการ</button></div>
    <div className="library-status" aria-label="กรองสถานะ">{[["active","ทั้งหมดที่ใช้งาน"],["pending","รอตรวจ"],["draft","ฉบับร่าง"],["published","เผยแพร่แล้ว"],["archived","เก็บเข้าคลัง"]].map(([value,label])=><button key={value} aria-pressed={status===value} onClick={()=>{setStatus(value);setPage(1);}}>{label}<span>{entries.filter(e=>value==="active"?e.status!=="archived":e.status===value).length}</span></button>)}</div>
    <div className="library-tools"><label className="search-box"><Search size={19}/><input aria-label="ค้นหาเนื้อหา" placeholder="ค้นหาชื่อ ผู้สร้าง หรือหมวดหมู่…" value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}}/></label><label className="library-kind"><span>ประเภท</span><select aria-label="ประเภทเนื้อหา" value={kind} onChange={e=>{setKind(e.target.value);setPage(1);}}><option value="all">ทุกประเภท</option>{Object.entries(kindLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><span className="library-count">{items.length} รายการ · ล่าสุดก่อน</span></div>
    <div className="library-table-wrap"><table className="library-table"><thead><tr><th>ชื่อรายการ</th><th>ประเภท</th><th>สถานะ</th><th><span className="sr-only">จัดการ</span></th></tr></thead><tbody>{items.slice((current-1)*20,current*20).map(entry=>{const Icon=icons[entry.kind];return <tr key={entry.id}><td><div className="library-item"><span className="library-item-icon"><Icon size={22}/></span><div><button className="library-title" onClick={()=>edit(entry)}>{entry.title}</button><p>{entry.author} <span>·</span> {entry.category}</p></div></div></td><td className="library-type">{kindLabels[entry.kind]}</td><td><span className={`status status-${entry.status}`}><i/>{statusLabels[entry.status]}</span></td><td className="library-action"><button className="button" onClick={()=>entry.status==="pending"?review(entry):edit(entry)} aria-label={`${entry.status==="pending"?"ตรวจ":"แก้ไข"} ${entry.title}`}>{entry.status==="pending"?<ArrowUpRight size={17}/>:<Pencil size={16}/>}<span>{entry.status==="pending"?"ตรวจ":"แก้ไข"}</span></button></td></tr>;})}</tbody></table>{!items.length&&<div className="empty-state"><Search size={26}/><h2>ไม่พบรายการ</h2><p>ลองเปลี่ยนคำค้นหรือเลือกสถานะอื่น</p><button className="button" onClick={()=>{setQuery("");setKind("all");setStatus("active");}}>ล้างตัวกรอง</button></div>}</div>
    <div className="library-pagination"><span>{items.length?`${(current-1)*20+1}–${Math.min(current*20,items.length)} จาก ${items.length} รายการ`:"0 รายการ"}</span><div><button className="icon-button" aria-label="หน้าก่อนหน้า" disabled={current===1} onClick={()=>setPage(current-1)}><ChevronLeft size={18}/></button><span>หน้า {current} / {pages}</span><button className="icon-button" aria-label="หน้าถัดไป" disabled={current===pages} onClick={()=>setPage(current+1)}><ChevronRight size={18}/></button></div></div>
  </section>;
}
